Adding cells cli to path
linuxserver/docker-pydio-cells pull request #18
Opened 2024-05-17 08:56 UTC by arana198

Adding cells cli to path

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

 - [ ] I have read the [contributing](https://github.com/linuxserver/docker-pydio-cells/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

## Benefits of this PR and context:

## How Has This Been Tested?

## Source / References:

2024-05-17 13:20 UTC, Roxedus commented
This PR will not be merged until it also cater for amd64. We would also like it if it did not include another run directive.

2024-05-17 16:42 UTC, arana198 commented
> This PR will not be merged until it also cater for amd64. We would also like it if it did not include another run directive.

Updated the pr

2024-05-21 11:45 UTC, arana198 commented
@Roxedus any chance you can look at this PR?

2024-05-27 20:04 UTC, Roxedus requested changes

2024-05-27 20:04 UTC, Roxedus commented on Dockerfile
> +  export PATH=/app/:$PATH && \
PATH can, and should be set a a part of ENV in the dockerfile, much like [this](https://github.com/linuxserver/docker-baseimage-alpine/blob/c4951e7021be5ba59d1fb93a6a6fbb7a92ba78a2/Dockerfile#L69)

2024-05-27 20:04 UTC, Roxedus commented on Dockerfile
> -COPY root/ /
Do not reorganize the structure of the dockerfile (the directory does need to exist when getting added to path).

2024-06-01 11:29 UTC, Roxedus approved these changes

2024-06-01 11:30 UTC, merged